mappings:
  NotificationService: WebTorque\Notifications\NotificationService
  NotificationAjaxServiceTrait: WebTorque\Notifications\Traits\NotificationAjaxServiceTrait
  NotificationResponse: WebTorque\Notifications\NotificationResponse
  NotificationDeliveryInterface: WebTorque\Notifications\Interfaces\NotificationDeliveryInterface
  NotificationProviderInterface: WebTorque\Notifications\Interfaces\NotificationProviderInterface
  NotificationAjaxServiceInterface: WebTorque\Notifications\Interfaces\NotificationAjaxServiceInterface
  NotificationServiceInterface: WebTorque\Notifications\Interfaces\NotificationServiceInterface
  ParsedNotificationInterface: WebTorque\Notifications\Interfaces\ParsedNotificationInterface
  NotificationResponseInterface: WebTorque\Notifications\Interfaces\NotificationResponseInterface
  NotificationParserInterface: WebTorque\Notifications\Interfaces\NotificationParserInterface
  NotificationSmsMessageMediaProvider: WebTorque\Notifications\Providers\NotificationSmsMessageMediaProvider
  NotificationDataObjectProvider: WebTorque\Notifications\Providers\NotificationDataObjectProvider
  NotificationEmailProvider: WebTorque\Notifications\Providers\NotificationEmailProvider
  MemberNotificationExtension: WebTorque\Notifications\MemberNotificationExtension
  NotificationParser: WebTorque\Notifications\NotificationParser
  ParsedNotification: WebTorque\Notifications\ParsedNotification
  NotificationFailureException: WebTorque\Notifications\Exceptions\NotificationFailureException
  NotificationDelivery: WebTorque\Notifications\Deliveries\NotificationDelivery
  NotificationDataObjectDelivery: WebTorque\Notifications\Deliveries\NotificationDataObjectDelivery
  NotificationPurgeTask: WebTorque\Notifications\NotificationPurgeTask
  NotificationType: WebTorque\Notifications\Models\NotificationType
  Notification: WebTorque\Notifications\Models\Notification
  NotificationAdmin: WebTorque\Notifications\Admin\NotificationAdmin
  NotificationParserTest: WebTorque\Notifications\Tests\NotificationParserTest
  NotificationPurgeTaskTest: WebTorque\Notifications\Tests\NotificationPurgeTaskTest
  NotificationServiceTest: WebTorque\Notifications\Tests\NotificationServiceTest
  MockParser: WebTorque\Notifications\Tests\MockParser
  MockBadParser: WebTorque\Notifications\Tests\MockBadParser
  MockNotificationProvider: WebTorque\Notifications\Tests\MockNotificationProvider
  MockBadNotificationProvider: WebTorque\Notifications\Tests\MockBadNotificationProvider
  MockNotificationDelivery: WebTorque\Notifications\Tests\MockNotificationDelivery
  NotificationEmailProviderTest: WebTorque\Notifications\Tests\Providers\NotificationEmailProviderTest
  NotificationDataObjectProviderTest: WebTorque\Notifications\Tests\Providers\NotificationDataObjectProviderTest
  NotificationSmsMessageMediaProviderTest: WebTorque\Notifications\Tests\Providers\NotificationSmsMessageMediaProviderTest
  MockParsedNotification: WebTorque\Notifications\Tests\Mocks\MockParsedNotification
  MockParsedNotificationWithoutSystemSubject: WebTorque\Notifications\Tests\Mocks\MockParsedNotificationWithoutSystemSubject
  MockMemberedNotificationProvider: WebTorque\Notifications\Tests\Mocks\MockMemberedNotificationProvider
  MockMemberedParser: WebTorque\Notifications\Tests\Mocks\MockMemberedParser
  MockMemberedParsedNotification: WebTorque\Notifications\Tests\Mocks\MockMemberedParsedNotification
  MockMemberedNotificationDelivery: WebTorque\Notifications\Tests\Mocks\MockMemberedNotificationDelivery
  MockBadParsedNotification: WebTorque\Notifications\Tests\Mocks\MockBadParsedNotification
  ParsedNotificationTest: WebTorque\Notifications\Tests\ParsedNotificationTest
  NotificationTypeTest: WebTorque\Notifications\Tests\Models\NotificationTypeTest
  NotificationTest: WebTorque\Notifications\Tests\Models\NotificationTest

